# Site settings
title: Edgar Rodriguez
email: edgar@rodr.io
description: > # this means to ignore newlines until "baseurl:"
  I am an Engineer and I work on AI, Semantic Web, Graph Analytics
  and Distributed Systems. I write code.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rodr.io" # the base hostname & protocol for your site
twitter_username: edgarRd
github_username:  edgarRd

# Build settings
markdown: kramdown
