# Harmony Jekyll theme general configurations

# Base URL
baseurl: ''

# Site live URL
# url: http://rodr.io

# Localhost
url: http://127.0.0.1:4000

# Harmony theme configuration. Please change accordingly.
harmony:
  name: Edgar Rodriguez-Diaz
  # Little description about your site
  description: My personal blog
  # 'meta_description:' Write an awesome description for your new site here.
  # It will appear in your document head meta (for Google search results) and
  # in your feed.xml site description.
  meta_description: > #
    I am an Engineer and I work on AI,
    Semantic Web, Graph Analytics and Distributed Systems.
    I write code.
  basetheme: theme-base-08 # pre defined thmes are darken, blue-water, redish.
  author: # Author details
    name: Edgar Rodriguez-Diaz
    email: edgar@rodr.io
    url: http://rodr.io

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-xxxx-x

  # Profile links, leave blank to ignore
  social:
    github: edgarRd
    twitter: edgarRd
  # Toggle disclaimer in footer
  show_disclaimer: false

# Conversion / Build settings
markdown:    kramdown
# This is how you put pygments config in jekyll 2.0 instead of pygments: true
highlighter: pygments

# Permalinks
permalink:        pretty

exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed
